### ISSUE TITLE
An OpenStack application tutorial should use OpenStack projects

### ISSUE THREAD

**Issue by everett-toews** [berendt/openstack-application-tutorial#2]
IMO, an OpenStack application tutorial should demonstrate the full capabilities an OpenStack cloud. As it stands now, this application only uses Nova. OpenStack clouds are much more that just compute. They should be viewed holistically as many projects working together to make life easier for developers. An OpenStack application should exemplify this. 

For example:

* Instead of Ansible use Heat
* Instead of RabbitMQ use Zaqar
* Instead of MySQL use MySQL but created by Trove
* Save and store the result images in Swift

I can understand the use of Ansible and compute only if this were intended to be an application that can be run on any cloud. Makes perfect sense in that scenario but this is supposed to be an OpenStack Application tutorial.

**Comment by berendt** [comment]
Thanks for your feedback. Please try to join the Hangout tomorrow for a demonstration of the application and further discussions.

http://lists.openstack.org/pipermail/user-committee/2015-March/000356.html

The Vagrant environment and Ansible is only used for local tests/demonstrations and development.

In the upcoming documentation we will work with this application. This application will be used to demonstrate how to use the components of OpenStack with an application. E.g. we bootstrap the application with Heat, we automatically scale the worker instances with Heat/Ceilometer, we use Trove to provide the database, we add support to directly push the images to Swift or Manila, we add support for Zaqar, we use Sahara to calculate the fractals, we use Neutron to provide a loadbalancer for the webinterface and API, we use MagnetoDB as database backend for the API service, we use Ceilometer to measure the calculation times, ...

Maybe the project name is not fully correct and should be `openstack-application-tutorial-application`, because the application will be used inside the OpenStack application tutorial. I will discuss this tomorrow in the hangout.

**Comment by fifieldt** [comment]
Yeah, just to clarify quickly - this tutorial is not about the application, it's about educating folks on a select few API calls (via SDKs).  This is not a reference application, and the tutorial itself is not designed to demonstrate the full capabilities of OpenStack - just first steps.

A more full explanation can be found at: https://www.youtube.com/watch?v=ahc5IsUdeK0

Having said that, as Christian mentions, we're actually going to try and achieve some of the things you mentioned :)

**Comment by everett-toews** [comment]
Sorry but I'm unable to join you for the hangout. I just don't have any time to commit to this project.

Your explanation helps a lot. I have a better idea of the direction of this thing. Thanks for that!
